name: Build
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
      - "**.org"
      - ".github/**"

jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        version: [ 'ubuntu-latest']
    runs-on: ${{ matrix.version }}
    env:
      PROJECT_NAME: polylauncher
    steps:
      - uses: actions/checkout@v3
      - name: setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo check
 
