name: Release
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # schedule:
    # - cron: '0 18 * * 5'
  # push:
  #   branches: [ '*' ]
  #   paths-ignore:
  #     - "**/docs/**"
  #     - "**.md"
  #     - "**.org"

jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        version: [ 'ubuntu-latest']
    runs-on: ${{ matrix.version }}
    env:
      PROJECT_NAME: polylauncher
    steps:
      - uses: actions/checkout@v3
      - name: setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo check
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: rust-template
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release # More information https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          semantic_version: 16
          # you can set branches for semantic-release above v16.
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
